[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "lib.sw"
license = "Apache-2.0"
name = "std"

[dependencies]
core = { git = "https://github.com/mitchmindtree/sway", branch = "implicit-core-std" }
